chore: add detailed description for BatchSize
openGemini/opengemini-client-go pull request #113
Opened 2024-07-17 15:38 UTC by xuthus5

fix: #112

2024-07-19 01:05 UTC, shoothzj commented
Can we add it to design doc first?

2024-07-21 14:10 UTC, Chenxulin97 approved these changes

2024-07-23 23:40 UTC, shoothzj requested changes
I think we should establish a mechanism to synchronize method descriptions, as they contain language-independent content.

2024-07-28 15:44 UTC, shoothzj approved these changes

2024-07-28 15:45 UTC, merged