feat: add description for Client interface
openGemini/opengemini-client-go pull request #114
Opened 2024-07-17 17:47 UTC by xuthus5

> Please do not merge requests until we have discussed the issue clearly.

Our open API should allow users to quickly understand how to use it, but at present, I still have misunderstandings about the definitions of ShowTagKeys and ShowSeries.

2024-07-19 01:05 UTC, shoothzj commented
Can we add it to design doc first?

2024-07-21 14:13 UTC, Chenxulin97 approved these changes

2024-07-23 23:40 UTC, shoothzj requested changes
I think we should establish a mechanism to synchronize method descriptions, as they contain language-independent content.

2024-09-06 23:26 UTC, xuthus5 commented
impl by: #165 , close it.

2024-09-06 23:26 UTC, closed without merging